/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tifKyQ927CK
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'
import { Rubik } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import Image from "next/image";

export function Homepage2() {

  // handle submit function to localhost 8000
  function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const formData = new FormData(event.currentTarget);
    const ip = formData.get("ip");
    const file = formData.get("file");
  
    if (!ip || !file) {
      console.error("IP address or file missing. Please fill in both fields.");
      return;
    }
  
    const uploadFile = async (fileData: File) => {
      try {
        const uploadFormData = new FormData();
        uploadFormData.append("file", fileData);
  
        const uploadResponse = await fetch("http://localhost:8000/upload/", {
          method: "POST",
          body: uploadFormData,
        });
  
        if (uploadResponse.ok) {
          const fileString = await uploadResponse.json();
          console.log(fileString.image_uri);
  
          // const parseFormData = new FormData();
          // parseFormData.append("file", fileString.image_uri);
  
          const parseResponse = await fetch(
            `http://localhost:8000/parse/?file=${fileString.image_uri}&sourceIP=${ip}`,
            {
              method: "POST",
              // body: parseFormData,
            }
          );
  
          if (parseResponse.ok) {
            const parsedData = await parseResponse.json();
            console.log("Parsed data:", parsedData);
            // redirect to the results page
            window.location.href = "/results";
          } else {
            console.error("Parsing failed. Error message:", parseResponse.statusText);
          }
        } else {
          console.error("Upload failed. Error message:", uploadResponse.statusText);
        }
      } catch (error) {
        console.error("An error occurred:", error);
      }
    };
  
    uploadFile(file as File);
  }
  
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link
          href="#"
          className="flex items-center justify-center"
          prefetch={false}
        >
          <RadarIcon className="h-6 w-6" />
          <span className="sr-only">TARDIS</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            Features
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            About
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 ||  mx-auto grid items-center  gap-6 px-10 py-12 lg:grid-cols-2 lg:gap-12">
          <div className="container px-4 md:px-6 ">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    Threat Analysis, Reconnaissance, and Data Intelligence
                  </h1>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl">
                    TARDIS is a powerful tool that analyzes STIX files to
                    provide comprehensive threat intelligence and
                    recommendations for your organization.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Upload STIX File
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Learn More
                  </Link>
                </div>
              </div>
            </div>
          </div>

          <img
            src="https://nsfocusglobal.com/wp-content/uploads/2017/02/Threat-Analysis.jpg"
            alt="TARDIS Features"
            className="rounded-xl object-cover"
            // style={{ aspectRatio: "600/400", objectFit: "cover" }}
          />
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">
                  Key Features
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Powerful Threat Intelligence
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  TARDIS analyzes STIX files to provide comprehensive threat
                  intelligence, including indicators of compromise, threat actor
                  profiles, and recommended mitigation strategies.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <img
                src="https://nsfocusglobal.com/wp-content/uploads/2017/02/Threat-Analysis.jpg"
                alt="TARDIS Features"
                className="rounded-xl object-cover"
                style={{ aspectRatio: "600/400", objectFit: "cover" }}
              />
              <div className="flex flex-col justify-center space-y-4">
                <ul className="grid gap-6">
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Threat Analysis</h3>
                      <p className="text-muted-foreground">
                        Identify and analyze potential threats to your
                        organization.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Reconnaissance</h3>
                      <p className="text-muted-foreground">
                        Gather intelligence on threat actors and their
                        activities.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Data Intelligence</h3>
                      <p className="text-muted-foreground">
                        Leverage data-driven insights to enhance your security
                        posture.
                      </p>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                Analyze STIX Files with TARDIS
              </h2>
              <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Upload a STIX file to TARDIS and get comprehensive threat
                intelligence and recommendations to enhance your security
                posture.
              </p>
            </div>
            <div className="mx-auto w-full max-w-lg space-y-2">
              <form className="" onSubmit={handleSubmit}>
                <div className="flex gap-2 p-2">
                  <Input name="ip" placeholder="IP address" className="max-w-lg flex-1" />
                  <Input
                    name="file"
                    type="file"
                    placeholder="Upload STIX file"
                    className="max-w-lg flex-1"
                  />
                </div>

                <Button type="submit">Analyze</Button>
              </form>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">
          &copy; 2024 TARDIS. All rights reserved.
        </p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4"
            prefetch={false}
          >
            Terms of Service
          </Link>
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4"
            prefetch={false}
          >
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  );
}

function RadarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19.07 4.93A10 10 0 0 0 6.99 3.34" />
      <path d="M4 6h.01" />
      <path d="M2.29 9.62A10 10 0 1 0 21.31 8.35" />
      <path d="M16.24 7.76A6 6 0 1 0 8.23 16.67" />
      <path d="M12 18h.01" />
      <path d="M17.99 11.66A6 6 0 0 1 15.77 16.67" />
      <circle cx="12" cy="12" r="2" />
      <path d="m13.41 10.59 5.66-5.66" />
    </svg>
  );
}
